//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VizeNotHesaplama
{
    using System;
    using System.Collections.Generic;
    
    public partial class OgrenciBilgileri
    {
        public int OgrenciID { get; set; }
        public string OgrenciAdi { get; set; }
        public string OgrenciSoyadi { get; set; }
        public int OgrenciVizeNot { get; set; }
        public int OgrenciFinalNot { get; set; }
        public int OgrenciOrtalama { get; set; }
        public string OgrenciHarfNotu { get; set; }
    }
}
